#!/bin/bash

# Required: gh CLI must be installed and authenticated (gh auth login)

REPO="eccentriccoder01/YourRepoName" # Replace with your full repo path
MAX_RETRIES=3

echo "Fetching merged PRs for $REPO..."

gh pr list --state merged --limit 200 --repo "$REPO" --json number,title,body > merged_prs.json

jq -c '.[]' merged_prs.json | while read -r pr; do
  pr_number=$(echo "$pr" | jq -r '.number')
  pr_title=$(echo "$pr" | jq -r '.title')
  pr_body=$(echo "$pr" | jq -r '.body')
  
  # Try to extract linked issue number from title/body (e.g. "#12")
  issue_number=$(echo "$pr_title $pr_body" | grep -oE '#[0-9]+' | head -n 1 | tr -d '#')

  if [ -z "$issue_number" ]; then
    echo "❌ PR #$pr_number has no linked issue."
    continue
  fi

  echo "🔗 PR #$pr_number linked to issue #$issue_number"

  # Fetch labels from the linked issue
  issue_labels=$(gh issue view "$issue_number" --repo "$REPO" --json labels | jq -r '.labels[].name')

  if [ -z "$issue_labels" ]; then
    echo "⚠️  Issue #$issue_number has no labels."
    continue
  fi

  # Add each label to the PR with retry logic
  for label in $issue_labels; do
    success=false
    for attempt in $(seq 1 $MAX_RETRIES); do
      echo "🏷️  Applying label '$label' to PR #$pr_number (Attempt $attempt)..."
      gh pr edit "$pr_number" --repo "$REPO" --add-label "$label" && success=true && break
      echo "⚠️  Failed to apply label '$label' (Attempt $attempt). Retrying in 2s..."
      sleep 2
    done

    if ! $success; then
      echo "❌ Giving up on label '$label' after $MAX_RETRIES attempts."
    fi
  done

  # Delay to avoid rate-limiting
  sleep 0.5

done

echo "✅ Done syncing labels."
