name: Label Merged PRs from Linked Issues

on:
  workflow_dispatch:
  # Uncomment to run nightly:
  # schedule:
  #   - cron: '0 1 * * *'

jobs:
  label-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (needed by GH CLI)
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        uses: cli/cli-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync labels from issues to merged PRs
        run: |
          set -eo pipefail

          echo "Fetching all closed PRs (may take time)..."
          gh api -H "Accept: application/vnd.github+json" \
            repos/${{ github.repository }}/pulls?state=closed \
            --paginate > prs.json

          echo "Processing each merged PR..."

          jq -c '.[] | select(.merged_at != null)' prs.json | while read -r pr; do
            pr_number=$(echo "$pr" | jq -r '.number')
            pr_body=$(echo "$pr" | jq -r '.body')

            # Try to extract issue number from body (e.g., #123)
            issue_number=$(echo "$pr_body" | grep -oE '#[0-9]+' | grep -oE '[0-9]+' | head -n1)

            if [ -z "$issue_number" ]; then
              echo "❌ No linked issue in PR #$pr_number"
              continue
            fi

            echo "🔄 PR #$pr_number links to issue #$issue_number"

            # Get labels from the issue
            issue_labels=$(gh api repos/${{ github.repository }}/issues/$issue_number | jq -r '.labels[].name')

            if [ -z "$issue_labels" ]; then
              echo "⚠️  No labels found on issue #$issue_number"
              continue
            fi

            # Add each label to the PR
            for label in $issue_labels; do
              echo "🏷️  Adding label '$label' to PR #$pr_number"
              gh api -X POST repos/${{ github.repository }}/issues/$pr_number/labels \
                -f labels[]="$label"
              sleep 0.3
            done

          done || echo "⚠️  Parsing or pipe failure handled gracefully"
