name: Sync Issue Labels to PR

on:
  workflow_dispatch:  # Manual trigger

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run label sync script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api -H "Accept: application/vnd.github+json" \
            repos/${{ github.repository }}/pulls?state=closed \
            --paginate > prs.json

          jq -c '.[] | select(.merged_at != null)' prs.json | while read pr; do
            pr_number=$(echo "$pr" | jq -r '.number')
            pr_body=$(echo "$pr" | jq -r '.body')

            issue_number=$(echo "$pr_body" | grep -oE '#[0-9]+' | grep -oE '[0-9]+' | head -n1)

            if [ -n "$issue_number" ]; then
              issue_labels=$(gh api repos/${{ github.repository }}/issues/$issue_number | jq -r '.labels[].name')
              
              for label in $issue_labels; do
                echo "Adding label '$label' to PR #$pr_number"
                gh api -X POST repos/${{ github.repository }}/issues/$pr_number/labels \
                  -f labels[]="$label"
              done
            fi
          done
