name: Sync Labels from Issues to Merged PRs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # Optional: runs every day at 2 AM UTC

jobs:
  sync-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq
      
      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch merged PRs and sync labels from issues
        env:
          REPO: eccentriccoder01/talkheal
          MAX_RETRIES: 3
        run: |
          echo "📥 Fetching merged PRs for $REPO..."
          gh pr list --state merged --limit 100 --repo "$REPO" --json number,title,body > merged_prs.json

          jq -c '.[]' merged_prs.json | while read -r pr; do
            pr_number=$(echo "$pr" | jq -r '.number')
            pr_title=$(echo "$pr" | jq -r '.title')
            pr_body=$(echo "$pr" | jq -r '.body')

            issue_number=$(echo "$pr_title $pr_body" | grep -oE '#[0-9]+' | head -n 1 | tr -d '#')

            if [ -z "$issue_number" ]; then
              echo "❌ PR #$pr_number has no linked issue."
              continue
            fi

            echo "🔗 PR #$pr_number linked to issue #$issue_number"

            issue_labels=$(gh issue view "$issue_number" --repo "$REPO" --json labels | jq -r '.labels[].name')

            if [ -z "$issue_labels" ]; then
              echo "⚠️  Issue #$issue_number has no labels."
              continue
            fi

            while IFS= read -r label; do
              success=false
              for attempt in $(seq 1 $MAX_RETRIES); do
                echo "🏷️  Applying label '$label' to PR #$pr_number (Attempt $attempt)..."
                if gh pr edit "$pr_number" --repo "$REPO" --add-label "$label"; then
                  success=true
                  break
                fi
                echo "⚠️  Failed to apply label '$label'. Retrying in 2s..."
                sleep 2
              done

              if [ "$success" = false ]; then
                echo "❌ Giving up on label '$label' after $MAX_RETRIES attempts."
              fi
            done <<< "$issue_labels"

            sleep 0.5
          done

          echo "✅ Done syncing labels."
